// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<$models.AllUsage>}
 */
export function FetchUsage() {
    return $Call.ByID(749438405).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.AppConfig>}
 */
export function GetSettings() {
    return $Call.ByID(4121742087).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function QuitApp() {
    return $Call.ByID(310939844);
}

/**
 * @param {string} zaiToken
 * @param {string} claudeSession
 * @param {string} openCodeCookie
 * @returns {$CancellablePromise<void>}
 */
export function SaveSettings(zaiToken, claudeSession, openCodeCookie) {
    return $Call.ByID(1381577550, zaiToken, claudeSession, openCodeCookie);
}

/**
 * StartPolling is kept for compatibility but does nothing
 * @returns {$CancellablePromise<void>}
 */
export function StartPolling() {
    return $Call.ByID(1366391425);
}

// Private type creation functions
const $$createType0 = $models.AllUsage.createFrom;
const $$createType1 = $models.AppConfig.createFrom;
