// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AllUsage {
    /**
     * Creates a new AllUsage instance.
     * @param {Partial<AllUsage>} [$$source = {}] - The source object to create the AllUsage.
     */
    constructor($$source = {}) {
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updatedAt"] = "";
        }
        if (!("providers" in $$source)) {
            /**
             * @member
             * @type {ProviderUsage[]}
             */
            this["providers"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AllUsage instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AllUsage}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("providers" in $$parsedSource) {
            $$parsedSource["providers"] = $$createField1_0($$parsedSource["providers"]);
        }
        return new AllUsage(/** @type {Partial<AllUsage>} */($$parsedSource));
    }
}

export class AppConfig {
    /**
     * Creates a new AppConfig instance.
     * @param {Partial<AppConfig>} [$$source = {}] - The source object to create the AppConfig.
     */
    constructor($$source = {}) {
        if (!("zaiToken" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["zaiToken"] = "";
        }
        if (!("claudeSession" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["claudeSession"] = "";
        }
        if (!("openCodeCookie" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["openCodeCookie"] = "";
        }
        if (!("providerOrder" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["providerOrder"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AppConfig}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("providerOrder" in $$parsedSource) {
            $$parsedSource["providerOrder"] = $$createField3_0($$parsedSource["providerOrder"]);
        }
        return new AppConfig(/** @type {Partial<AppConfig>} */($$parsedSource));
    }
}

export class Metric {
    /**
     * Creates a new Metric instance.
     * @param {Partial<Metric>} [$$source = {}] - The source object to create the Metric.
     */
    constructor($$source = {}) {
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("used" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["used"] = 0;
        }
        if (!("max" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["max"] = 0;
        }
        if (!("pct" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pct"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Metric instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Metric}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Metric(/** @type {Partial<Metric>} */($$parsedSource));
    }
}

export class ProviderUsage {
    /**
     * Creates a new ProviderUsage instance.
     * @param {Partial<ProviderUsage>} [$$source = {}] - The source object to create the ProviderUsage.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("metrics" in $$source)) {
            /**
             * @member
             * @type {Metric[]}
             */
            this["metrics"] = [];
        }
        if (!("resetIn" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["resetIn"] = "";
        }
        if (!("resetEpoch" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["resetEpoch"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProviderUsage instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProviderUsage}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("metrics" in $$parsedSource) {
            $$parsedSource["metrics"] = $$createField1_0($$parsedSource["metrics"]);
        }
        return new ProviderUsage(/** @type {Partial<ProviderUsage>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = ProviderUsage.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = Metric.createFrom;
const $$createType4 = $Create.Array($$createType3);
