// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<$models.AllUsage>}
 */
export function FetchUsage() {
    return $Call.ByID(3126757199).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.AppConfig>}
 */
export function GetSettings() {
    return $Call.ByID(3456757617).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function QuitApp() {
    return $Call.ByID(437051418);
}

/**
 * @param {string} zaiToken
 * @param {string} claudeSession
 * @returns {$CancellablePromise<void>}
 */
export function SaveSettings(zaiToken, claudeSession) {
    return $Call.ByID(1691659760, zaiToken, claudeSession);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function StartPolling() {
    return $Call.ByID(463951903);
}

// Private type creation functions
const $$createType0 = $models.AllUsage.createFrom;
const $$createType1 = $models.AppConfig.createFrom;
